# Generated by Django 4.1.1 on 2022-11-23 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='created_date_ad',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
