# Generated by Django 4.1.1 on 2022-11-24 09:28

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_booking_created_date_ad_alter_booking_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='booking.booking'),
        ),
    ]
