# Generated by Django 4.1.1 on 2022-11-24 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_booking_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='parent',
        ),
    ]
