# Generated by Django 4.1.1 on 2022-11-27 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_remove_booking_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='room',
        ),
    ]
