# Generated by Django 4.1.1 on 2022-09-20 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='max_length can be upto 100 characters', max_length=100)),
                ('number', models.IntegerField()),
                ('room_status', models.IntegerField(choices=[(1, 'IN-USE'), (2, 'VACANT'), (3, 'BOOKED')], default=2, help_text='room status : 1 = IN-USE, 2 = VACANT, default value is = 2')),
                ('active', models.BooleanField(default=True, help_text='default= True')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created_date_ad', models.DateTimeField()),
            ],
        ),
    ]
