# Generated by Django 4.1.1 on 2022-11-24 09:40

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_remove_room_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='rooms.room'),
        ),
    ]
