# Generated by Django 4.1.1 on 2022-11-27 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_remove_booking_room'),
        ('rooms', '0006_remove_room_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='booking',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='booking.booking'),
        ),
    ]
