# Generated by Django 4.1.1 on 2022-11-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='id_card_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='id_card_type',
            field=models.PositiveIntegerField(choices=[(1, 'CITIZENSHIP'), (2, 'PASSPORT'), (3, 'DRIVING LICENSE'), (4, 'OTHERS')], default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='mobile_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
